theme:
  name: material

site_name: WailSalutem Digital learning wiki

nav:
  - Home: index.md
  - Documentation:
    - Cooperation agreement: documentation/cooperation-agreement.md
    - UML Diagram: documentation/uml-diagram.md
    - Use Case diagram: documentation/use-case-diagram.md
    - Interviews:
      - Interview questions: documentation/interviews/interview-questions.md
  - Developers:
    - Working with Git: developers/working-with-git.md