sonar.organization=al3ksandrs
sonar.projectKey=al3ksandrs_wailsalutem-digital-learning

# Relative path to source directories
sonar.sources=.

# Encoding of the source code
sonar.sourceEncoding=UTF-8

# Exclusions
# Added: server/index.ts and everything inside server/scripts/
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.spec.ts,**/*.test.ts,**/*.test.tsx,server/index.ts,server/scripts/**/*