sonar.organization=al3ksandrs
sonar.projectKey=al3ksandrs_wailsalutem-digital-learning
sonar.sourceEncoding=UTF-8

# Where source code is
sonar.sources=client/src,server/
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.spec.ts,**/*.spec.tsx,**/*.test.ts,**/*.test.tsx,**/tests/**

# Where tests are
sonar.tests=client/src,server/
sonar.test.inclusions=**/*.spec.ts,**/*.spec.tsx,**/*.test.ts,**/*.test.tsx

# Coverage paths
sonar.javascript.lcov.reportPaths=client/coverage/lcov.info,server/coverage/lcov.info