sonar.organization=al3ksandrs
sonar.projectKey=al3ksandrs_wailsalutem-digital-learning

# Relative path to source directories
sonar.sources=.
sonar.tests=.

# Encoding of the source code
sonar.sourceEncoding=UTF-8

# Test files
sonar.test.inclusions=**/*.spec.ts,**/*.spec.tsx,**/*.test.ts,**/*.test.tsx

# Exclusions
sonar.exclusions=**/node_modules/**,**/dist/**

# Scans both client and server since we use a monorepo
sonar.javascript.lcov.reportPaths=./client/coverage/lcov.info,./server/coverage/lcov.info