name: CD

on:
  workflow_dispatch:  # Manual trigger for now

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


        # Deployment steps here in the future when Rachid provides the VPS servers for both frontend and server.
        # Docker will be used!

      - run: echo "CD pipeline placeholder. No deploy steps yet..."
