name: CI

on:
  pull_request:
  push:
    # If we in the future want CI to run on every branch. This will require more runner minutes!
    # branches: ["development", "main", "feat/*", "fix/*", "test/*", "refactor/*"]
    branches: ["development", "main"]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # Required for SonarQube analysis

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          # Disabled cache for now to test if this is causing the error
          #cache: 'npm'

      - name: Install dependencies
        run: |
          rm package-lock.json
          npm install

      # Runs client side tests and generates a report
      - name: Run Client Tests
        run: npm run test:coverage --workspace=client

      # Verifies that TypeScript compiles without errors in the client side
      - name: Build Client
        run: npm run build --workspace=client

      # SonarCloud scan (SonarQube on their cloud)
      - name: SonarCloud Scan
        # SonarQube likes to cry about numerical versions so we have to put a SHA of the commit ID here. (we use v6 here)
        uses: SonarSource/sonarqube-scan-action@fd88b7d7ccbaefd23d8f36f73b59db7a3d246602
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}