name: CI

on:
  pull_request:
  push:
    # If we in the future want CI to run on every branch. This will require more runner minutes!
    # branches: ["development", "main", "feat/*", "fix/*", "test/*", "refactor/*"]
    branches: ["development", "main"]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # Required for SonarQube analysis

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: |
          rm -f package-lock.json
          npm install

      # Runs tests to see coverage
      - name: Run Client Tests with Coverage
        run: npm run test:coverage --workspace=client

      # Vitest thinks files are in 'src/', but Sonar needs to know they are in 'client/src/'
      - name: Fix Coverage Paths
        run: |
          sed -i 's|SF:src/|SF:client/src/|g' client/coverage/lcov.info

      # SonarCloud scan (SonarQube on their cloud)
      - name: SonarCloud Scan
        # SonarQube likes to cry about numerical versions so we have to put a SHA of the commit ID here. (we use v6 here)
        uses: SonarSource/sonarqube-scan-action@fd88b7d7ccbaefd23d8f36f73b59db7a3d246602
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
