name: CI

on:
  pull_request:
  push:
    # If we in the future want CI to run on every branch. This will require more runner minutes!
    # branches: ["development", "main", "feat/*", "fix/*", "test/*", "refactor/*"]
    branches: ["development", "main"]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # Required for SonarQube analysis

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci